title: matkv
author: matkv
email: 
description: > # this means to ignore newlines until "show_exerpts:"
  This website is a personal wiki for C#, Python, Kotlin, Flutter & Android development
  and for learning Linux & Blender.

show_excerpts: true # set to true to show excerpts on the homepage

markdown: kramdown
highlighter: rouge

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%-d. %B %Y"

  # generate social links in footer
  social_links:
    twitter: matkobusljeta
    github:  matkv
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - Blog.md
  - Android.md
  - Blender.md
  - Csharp.md
  - Flutter.md
  - Kotlin.md
  - Linux.md
  - Python.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- _includes/head.html
- History.markdown